--local takeOff = 2500
--local phi = {1400, 1200, 1000, 800, 600, 400, 200}
--local m_i = 7
--local flag = 10
--
--function app_a1()
--    current_nav = mission:get_current_nav_index()
--    if flag == 0 and current_nav == 1 then
--        param:set("LIM_PITCH_MAX", takeOff)
--        param:set("LIM_PITCH_MIN", -takeOff)
--
--        pitchLim = param:get("LIM_PITCH_MAX")
--        message = "Current pitch limit is set to " .. pitchLim
--        gcs:send_text(0, message)
--        flag = 1
--    end
--    if current_nav >= 2 and flag == 1 then 
--        param:set("LIM_PITCH_MAX", phi[m_i])
--        param:set("LIM_PITCH_MIN", -phi[m_i])
--        flag = 2
--
--        pitchLim = param:get("LIM_PITCH_MAX")
--        
--        --Comfirming mission
--        message = "Current angle is given by " .. phi[m_i] .. " and current pitch lim is set to " .. pitchLim
--        gcs:send_text(0, message)
--        
--    end
--    return app_a1, 1000
--end
--
--return app_a1(), 1000